command /roulette [<integer>] [<integer>] [<integer>] [<integer>] [<integer>] [<integer>]:
    trigger:
        set {x1} to arg-1
        set {y1} to arg-2
        set {z1} to arg-3
        set {x2} to arg-4
        set {y2} to arg-5
        set {z2} to arg-6
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.0 from block %{x2}% %{y2}% %{z2}% container.0"
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.1 from block %{x2}% %{y2}% %{z2}% container.1"
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.2 from block %{x2}% %{y2}% %{z2}% container.2"
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.3 from block %{x2}% %{y2}% %{z2}% container.3"
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.4 from block %{x2}% %{y2}% %{z2}% container.4"
        execute console command "item replace block %{x1}% %{y1}% %{z1}% container.5 from block %{x2}% %{y2}% %{z2}% container.5"